version: '3.8'
services:
  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=new_era_cars_application
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
